home/urls.py
from django.conf.urls import url
from django.contrib.auth import logout
from django.urls import path

from home import views

app_name = 'home'
urlpatterns = [
    path('', views.index_page, name='home'),
]

which_person/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('home.urls'), name='account_index'),
    path('which_person/', include('which_person_themes.urls')),
]

which_person_themes/urls.py
from django.conf.urls import url
from django.contrib.auth import logout
from django.urls import path
from which_person_themes import views

app_name = 'which_person_themes'
urlpatterns = [
    path('', views.themes_list, name='home'),
    path('add/', views.ThemeEditer.as_view(), name='add'),  # 登録
    path('mod/<int:theme_id>/', views.ThemeEditer.as_view(), name='mod'),  # 修正
    path('which/<int:theme_id>/', views.Vote.as_view(), name='which'),
    path('which/cancel/<int:theme_id>/', views.ThemeCanceler.as_view(), name='which_cancel'),
    path('which/voting/<int:theme_id>/<int:choice_num>/', views.VoteingAPI.as_view(), name='voting_api'),
    path('which/can_voting/<int:theme_id>/', views.CanVoteingAPI.as_view(), name='can_voting_api'),
    path('which/vote_qty/<int:theme_id>/', views.VoteQtyGetAPI.as_view(), name='vote_qty_api'),
    path('which/vote_cancel/<int:theme_id>/', views.CancelVoteAPI.as_view(), name='vote_cancel_api'),
    path('which/comment_post/', views.CommentPostAPI.as_view(), name='comment_post_api'),
    path('which/comment_cancel/', views.CommentCancelAPI.as_view(), name='comment_cancel_api'),
    path('which/comment_list/<int:theme_id>/', views.CommentListGetAPI.as_view(), name='comment_list_api'),

]

which_person_themes/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

from django.db import models

class Theme(models.Model):
    name = models.CharField('お題名', max_length=255)
    major_class = models.CharField('大分類', max_length=255)
    medium_class = models.CharField('中分類', max_length=255)
    choice1 = models.TextField('選択肢1', max_length=255)
    choice2 = models.TextField('選択肢2', max_length=255)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

class Voting(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE)
    choice_num = models.IntegerField('選択肢番号')

class Comment(models.Model):
    user_name = models.CharField('ユーザ名', max_length=255)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE)
    choice_num = models.IntegerField('選択肢番号')
    comment = models.CharField('コメント', max_length=512)

which_person_themes/views.py
import json
import logging

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.views.generic.base import View
from django.core import serializers
from rest_framework.generics import RetrieveUpdateAPIView
from rest_framework.response import Response
from rest_framework.views import APIView

from which_person_themes.form import ThemeForm
from which_person_themes.models import Theme, Voting, Comment
from which_person_themes.serializers import CommnetSerializer


def themes_list(request):
    """書籍の一覧"""
    # return HttpResponse('書籍の一覧')
    themes = Theme.objects.all().order_by('id')
    return render(request,
                  'theme_list.html',  # 使用するテンプレート
                  {'themes': themes})  # テンプレートに渡すデータ


class ThemeCanceler(View):
    def get(self, request, *args, **kwargs):
        try:
            theme_id = kwargs['theme_id']
        except KeyError:
            theme_id = None

        if theme_id and request.user is not None and Theme.objects.filter(pk=theme_id,
                                                                          user_id=request.user.id).exists():
            Theme.objects.filter(pk=theme_id, user_id=request.user.id).delete()

        return redirect('which_person_themes:home')


class ThemeEditer(View):
    def get(self, request, *args, **kwargs):
        try:
            theme_id = kwargs['theme_id']
        except KeyError:
            theme_id = None

        if theme_id:
            theme = get_object_or_404(Theme, pk=theme_id)
        else:
            theme = Theme()

        form = ThemeForm(instance=theme)

        return render(request, 'theme_edit.html', dict(form=form, theme_id=theme_id))

    def post(self, request, *args, **kwargs):
        try:
            theme_id = kwargs['theme_id']
        except KeyError:
            theme_id = None

        if theme_id:
            theme = get_object_or_404(Theme, pk=theme_id)
        else:
            theme = Theme()

        form = ThemeForm(request.POST, instance=theme)  # POST された request データからフォームを作成

        user = request.user

        if form.is_valid() and user is not None:  # フォームのバリデーション
            theme = form.save(commit=False)
            theme.user = user
            theme.save()

            return redirect('which_person_themes:home')

        return render(request, 'theme_edit.html', dict(form=form, theme_id=theme_id))


class Vote(LoginRequiredMixin, View):

    # @login_required
    def get(self, request, *args, **kwargs):

        try:
            theme_id = kwargs['theme_id']
        except KeyError:
            theme_id = -1

        theme = get_object_or_404(Theme, pk=theme_id)

        param = {'theme': theme, 'user_id': request.user.id}

        return render(request, 'which.html', param)


class VoteQtyGetAPI(LoginRequiredMixin, APIView):
    def get(self, request, *args, **kwargs):
        try:
            theme_id = kwargs['theme_id']
        except KeyError:
            result = {"get_success": False}
            return Response(result)

        choice1_qty = Voting.objects.filter(theme_id=theme_id, choice_num=1).count()
        choice2_qty = Voting.objects.filter(theme_id=theme_id, choice_num=2).count()

        result = {"get_success": True, "choice1_qty": choice1_qty, "choice2_qty": choice2_qty}
        return Response(result)


class VoteingAPI(LoginRequiredMixin, APIView):
    def get(self, request, *args, **kwargs):

        try:
            theme_id = kwargs['theme_id']
            choice_num = kwargs['choice_num']
        except KeyError:
            result = {"processing_success": False}
            return Response(result)

        theme = get_object_or_404(Theme, pk=theme_id)
        user = request.user

        voted = False
        if not Voting.objects.filter(theme_id=theme_id, user_id=user.id).exists():
            voting = Voting()
            voting.theme = theme
            voting.user = user
            voting.choice_num = choice_num
            voting.save()
            voted = True

        result = {"processing_success": True, "voted": voted}
        return Response(result)


class CanVoteingAPI(LoginRequiredMixin, APIView):
    def get(self, request, *args, **kwargs):
        try:
            theme_id = kwargs['theme_id']
        except KeyError:
            result = {"processing_success": False, "canVote": False}
            return Response(result)

        # ↓filterで取得しているが、実質1件となるはず。ひとつのお題に対して、1ユーザは1回までしか投票できないように制御済み
        if Voting.objects.filter(theme_id=theme_id, user_id=request.user.id).exists():
            vote = Voting.objects.filter(theme_id=theme_id, user_id=request.user.id)
            result = {"processing_success": True, "canVote": False, "choice_num": vote[0].choice_num}
            return Response(result)

        result = {"processing_success": True, "canVote": True}
        return Response(result)


class CancelVoteAPI(LoginRequiredMixin, APIView):
    def get(self, request, *args, **kwargs):
        try:
            theme_id = kwargs['theme_id']
        except KeyError:
            result = {"processing_success": False, "isCanceled": False}
            return Response(result)

        # ↓filterで取得しているが、実質1件となるはず。ひとつのお題に対して、1ユーザは1回までしか投票できないように制御済み
        if Voting.objects.filter(theme_id=theme_id, user_id=request.user.id).exists():
            deletingVote = Voting.objects.filter(theme_id=theme_id, user_id=request.user.id)
            deletingChoiceNum = deletingVote[0].choice_num

            Voting.objects.filter(theme_id=theme_id, user_id=request.user.id).delete()

            result = {"processing_success": True, "isCanceled": True, "canceledChoiceNum": deletingChoiceNum}
            return Response(result)

        result = {"processing_success": True, "isCanceled": False}
        return Response(result)


class CommentPostAPI(LoginRequiredMixin, APIView):
    def post(self, request, *args, **kwargs):
        theme_id = request.POST.get("theme_id")
        input_text = request.POST.get("input_text")

        logging.debug("theme_id : " + theme_id)
        logging.debug("input_text : " + input_text)

        theme = get_object_or_404(Theme, pk=theme_id)
        vote = get_object_or_404(Voting, theme_id=theme_id, user_id=request.user.id)

        if input_text:
            comment = Comment()
            comment.theme = theme
            comment.choice_num = vote.choice_num
            comment.user_name = request.user.username
            comment.comment = input_text
            comment.user = request.user
            comment.save()

            serializer = CommnetSerializer(comment)
            return JsonResponse(serializer.data)


class CommentCancelAPI(LoginRequiredMixin, APIView):
    def post(self, request, *args, **kwargs):
        comment_id = request.POST.get("comment_id")

        isCanceled = False

        if Comment.objects.filter(pk=comment_id, user_id=request.user.id).exists():
            Comment.objects.filter(pk=comment_id, user_id=request.user.id).delete()
            isCanceled = True

        result = {"isCanceled": isCanceled, "comment_id": comment_id}
        return Response(result)


class CommentListGetAPI(LoginRequiredMixin, APIView):
    def get(self, request, *args, **kwargs):
        try:
            theme_id = kwargs['theme_id']
        except KeyError:
            return JsonResponse({})

        dict = {}
        if Comment.objects.filter(theme_id=theme_id).exists():
            comments = Comment.objects.filter(theme_id=theme_id)

            for i, comment in enumerate(comments):
                dict[i] = CommnetSerializer(comment).data

        return JsonResponse(dict)

which_person_themes/templates/base.html
{% load i18n static %}
<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT"
            crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>


    {% block extra_css %}{% endblock %}
    <title>{% block title %}Which Person ?{% endblock %}</title>

    <div class="container-fluid">
        <div class="row sticky-top border-bottom">
            <div id="title_block" class="col-sm-12 pt-1 pb-1">
                <a href="{% url 'which_person_themes:home' %}"><h1>Which Person ?</h1></a>
            </div>
        </div>
    </div>
</head>
<body>

<div class="container">
    {% block content %}
        {{ content }}
    {% endblock %}
</div>

{% block extra_js %}{% endblock %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<script src="{% static 'js/Page.js' %}"></script>
</body>
</html>

which_person_themes/templates/test_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
</head>
<body>

{% load static %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">

<div class="container">

    <div class="row">
        <div class="col-3">
            <div class="sidebar_fixed">
                固定するコンテンツ
            </div>
        </div>
        <div class="col">
            メインコンテンツ
            <br>
            メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br> メインコンテンツ
            <br>
        </div>
    </div>
</div>

</body>
</html>

which_person_themes/templates/theme_edit.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block title %}お題追加{% endblock title %}

{% block content %}
    <h4 class="mt-4 mb-5 border-bottom">お題の追加</h4>
    {% if theme_id %}
    <form action="{% url 'which_person_themes:mod' theme_id=theme_id %}" method="post">
    {% else %}
    <form action="{% url 'which_person_themes:add' %}" method="post">
    {% endif %}
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'which_person_themes:home' %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

which_person_themes/templates/theme_list.html
{% extends "base.html" %}

{% block title %}ホーム{% endblock title %}

{% block content %}
    {% if user.id  %}
        <p>こんにちは，{{ user.username }}さん</p>
    {% else %}
        <p>ログインしていません</p>
    {% endif %}

    <h4 class="mt-4 border-bottom">テーマ一覧</h4>
    <a href="{% url 'which_person_themes:add' %}" class="btn btn-primary btn-sm my-3">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">お題</th>
          <th scope="col">操作</th>
        </tr>
      </thead>
      <tbody>
        {% for theme in themes %}
        <tr>
            <td>
                <a href="{% url 'which_person_themes:which' theme_id=theme.id %}">{{ theme.name }}</a>
            </td>

            <td>
                {% if theme.user_id == user.id  %}
                    <a href="{% url 'which_person_themes:mod' theme_id=theme.id %}" class="btn btn-outline-primary btn-sm">修正</a>
                    <a href="{% url 'which_person_themes:which_cancel' theme_id=theme.id %}" class="btn btn-outline-primary btn-sm">削除</a>
                {% endif %}
            </td>

        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock content %}

which_person_themes/templates/which.html
{% extends "base.html" %}
{% block title %}どっち派？{% endblock title %}
{% block content %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/which.css' %}">

    {{ theme.id|json_script:"theme_id" }}
    {{ user_id|json_script:"user_id" }}

    <div id="comment_parts" hidden>{% static 'html_parts/comment.html' %}</div>
    <div id="comment_delete_api" hidden>{% url 'which_person_themes:comment_cancel_api' %}</div>

    <div class="row pt-5">
        <div id="theme_name" class="col">
            <h3>{{ theme.name }}</h3>
        </div>
    </div>

    <div class="row">
        <div class="choice col-sm-6 pt-3 rounded-lg choice_pickup" id="choice_1">
            <div class=choice_name>
                {{ theme.choice1 | linebreaksbr }}
            </div>
            <span id="choice1_qty">
                &nbsp;&nbsp;
            </span>
            人
            <div class=vote_botton>
                <button data-choice_num="1"
                        data-href="{% url 'which_person_themes:voting_api' theme_id=theme.id choice_num=1 %}"
                        class="voting_btn btn btn-primary btn-sm my-3">投票する
                </button>
            </div>

        </div>
        <div class="choice col-sm-6 pt-3 rounded-lg choice_pickup" id="choice_2">
            <div class=choice>
                {{ theme.choice2 | linebreaksbr }}
            </div>
            <span id="choice2_qty">
                &nbsp;&nbsp;
            </span>
            人

            <div class=vote_botton>
                <button data-choice_num="2"
                        data-href="{% url 'which_person_themes:voting_api' theme_id=theme.id choice_num=2 %}"
                        class="voting_btn btn btn-primary btn-sm my-3">投票する
                </button>
            </div>
        </div>
    </div>


    <div class="row">
        <button class="btn btn-primary btn-sm my-3" id=vote_cancel_button>投票取り消し</button>
    </div>

    <div class="row">
        <p id="voted_message"></p>
    </div>


    {% csrf_token %}

    <div class="row mx-auto" id="comment_area">

        <div class="col" id="comment_message">

        </div>
    </div>

    <script src="{% static 'js/Voting.js' %}"></script>
    <script src="{% static 'js/VotingButton.js' %}"></script>
    <script src="{% static 'js/VoteCancelButton.js' %}"></script>
    <script src="{% static 'js/Comment.js' %}"></script>

    <footer class="fixed-bottom pb-5 pr-5">
        <div class="row">
            <div class="col">
                <button id="comment_post_button" type="button" class="btn btn-primary rounded-pill js-modal-open"
                        href="">
                    コメントを書く
                </button>
            </div>
            <div class="modal js-modal">
                <div class="modal__bg js-modal-close"></div>
                <div class="modal__content">
                    <form name="comment_form" id="comment_form"
                          action="{% url 'which_person_themes:comment_post_api' %}"
                          method="POST">
                        {% csrf_token %}
                        <textarea required id="id_input_text" name="input_text" style="width:100%;height:100%"
                                  rows="6"
                                  placeholder="自分の投票した選択肢へのコメントをどうぞ"></textarea>
                        <input type="hidden" type="text" name="theme_id" value={{ theme.id }}>
                        <br>
                        <input class="comment_btn" type="submit">
                    </form>
                    <a class="js-modal-close" href="">閉じる</a>
                </div><!--modal__inner-->
            </div><!--modal-->

        </div>

    </footer>



{% endblock content %}